### ISSUE TITLE
Iframe integration

### ISSUE THREAD

**Issue by sleptor** [Veriff/veriff-integration-guide#1]
You have recently provided some info about IFrames here
https://github.com/Veriff/veriff-integration-guide/blob/master/docs/2-generating-sessions.md#using-veriff-in-an-iframe

The question is do you have a special URL for using into IFrames?

Because the URL currently returned by Session API is not really suitable for that.
I don't need "Welcome to Veriff's online identity verification solution" header and etc. 

Also, everything must be more compact. Why should it take almost all screen 1000x650px?

**Comment by sleptor** [comment]
Also, there is some permission issue if open KYC URL in IFrame. If open the same URL directly in a browser then all ok

![image](https://user-images.githubusercontent.com/1132612/48626667-2a24a180-e9bb-11e8-8239-7b53f2c18748.png)

**Comment by oree** [comment]
Hi @sleptor !

Thank you for your questions.  The regular session URL is good for use in iFrame.

On Chrome, you have to give permissions to the iframe, using the "allow" attribute.
Please see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#Attributes
